name: Publish Nightly Package

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch: {}

jobs:
  publish-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: auto-update
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      # Update package.json with nightly version
      - name: Update package version for nightly
        id: version
        run: |
          cd json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          NIGHTLY_VERSION="${PACKAGE_VERSION}-nightly"
          echo "NIGHTLY_VERSION=${NIGHTLY_VERSION}" >> $GITHUB_ENV

          # Update package.json with nightly version
          npm version ${NIGHTLY_VERSION} --no-git-tag-version

      # Publish with nightly tag
      - run: npm publish --provenance --access public --tag nightly
        working-directory: ./json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
